### ISSUE TITLE
while uninstalling, it is not removing the folder in C drive

### ISSUE THREAD

**Issue by ranadheerrannu** [Yiidiir/printerplusplus#1]
While uninstalling the app, folder created in c drive during the installation is not getting deleted. Reason is we are creating a Temp folder manually inside the "C:\PrinterPlusPlus" folder. So installer is unable to delete this custom folder.

**Comment by Yiidiir** [comment]
@ranadheerrannu This repo is just a mirror, report issues on source tracker.
