### ISSUE TITLE
App is running multiple instances when clicked from Users Program Menu

### ISSUE THREAD

**Issue by ranadheerrannu** [Yiidiir/printerplusplus#2]
Once the installation is completed, a shortcut will be added in User Program Menu. We can click on it to run the app. But if the app is already running and if you click on it from program menu, it is creating multiple instances. May be we need to add a condition to check if the app is already running any instance.

**Comment by Yiidiir** [comment]
@ranadheerrannu This repo is just a mirror, report issues on source tracker.
